services:
  runner:
    image: gitlab/gitlab-runner:latest
    ports:
    - "${PORT:-8080}:80"
    volumes:
    - ./volumes/gitlab-runner:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
